# Generated by Django 5.2.16 on 2026-09-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0053_userimportjob_lease_token"),
        ("users", "0054_relevador_calle_provincia_unica"),
    ]

    operations = []
