# Generated by Django 5.2.16 on 2026-09-28 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizaciones", "0021_issue_2188_vencimiento_firmante_programa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacion",
            name="territoriales_abordaje_comunitario",
            field=models.ManyToManyField(
                blank=True,
                related_name="organizaciones_territorial_abordaje",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Territorial Asignado Abordaje Comunitario",
            ),
        ),
    ]
