/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/vpsl/actions/{kind}/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["actions_retrieve"];
        put?: never;
        post: operations["actions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpsl/exports/{kind}/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exports_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpsl/forms/{kind}/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["forms_retrieve"];
        put?: never;
        post: operations["forms_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpsl/itinerarios/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["vpsl_itinerarios_list"];
        put?: never;
        post: operations["vpsl_itinerarios_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpsl/itinerarios/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["vpsl_itinerario_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpsl/jornadas/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["jornadas_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpsl/jornadas/{id}/laboratorio/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["jornadas_laboratorio_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpsl/jornadas/{id}/registros/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["jornadas_registros_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpsl/options/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["options_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpsl/renaper/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["renaper_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpsl/sedes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["vpsl_sedes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpsl/sedes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["vpsl_sede_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpsl/session/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["session_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vpsl/ubicacion/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ubicacion_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `aprobar` - aprobar
         *     * `subsanar` - subsanar
         *     * `rechazar` - rechazar
         * @enum {string}
         */
        AccionEvaluacionEnum: "aprobar" | "subsanar" | "rechazar";
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        ActionInput: {
            accion_evaluacion?: components["schemas"]["AccionEvaluacionEnum"];
            carta_archivo_estado?: string;
            carta_referencia_estado?: string;
            subsanacion_observaciones?: string;
            casos?: number[];
            /** Format: date */
            fecha?: string;
            responsable?: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        ActionResult: {
            ok: boolean;
            message?: string;
            redirect?: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        Checklist: {
            item: string;
            descripcion: string;
            cumple: boolean | null;
            observacion: string;
            evidencia_url: string;
            historial: components["schemas"]["ChecklistHistory"][];
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        ChecklistHistory: {
            /** Format: date-time */
            fecha: string;
            antes: boolean | null;
            despues: boolean | null;
            observacion: string;
            responsable: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        ChecklistInput: {
            electricidad_cumple: string;
            electricidad_observacion?: string;
            /** Format: uri */
            electricidad_evidencia?: string;
            viandas_cumple: string;
            viandas_observacion?: string;
            /** Format: uri */
            viandas_evidencia?: string;
            seguridad_cumple: string;
            seguridad_observacion?: string;
            /** Format: uri */
            seguridad_evidencia?: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        Choice: {
            value: string;
            label: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        Cierre: {
            id: number;
            consistente: boolean;
            responsable: string;
            atenciones: number;
            lentes: number;
            casos: number;
            observaciones: string;
            acta_adjunta_url: string;
            historial: components["schemas"]["CierreHistory"][];
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        CierreHistory: {
            /** Format: date-time */
            fecha: string;
            responsable: string;
            atenciones: number;
            lentes: number;
            casos: number;
            acta_adjunta_url: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        CierreInput: {
            cantidad_atenciones_registradas: number;
            cantidad_lentes_entregados_dia: number;
            cantidad_casos_laboratorio_reportados: number;
            responsable_cierre: string;
            /** Format: uri */
            acta_adjunta?: string;
            observaciones?: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        DeleteBreakdown: {
            modelo_key: string;
            modelo: string;
            cantidad: number;
            modo: components["schemas"]["ModoEnum"];
            ejemplos: string[];
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        DeletePreview: {
            preview: components["schemas"]["DeleteSummary"];
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        DeleteSummary: {
            operacion: components["schemas"]["OperacionEnum"];
            total_afectados: number;
            total_baja_logica: number;
            total_borrado_fisico: number;
            desglose_por_modelo: components["schemas"]["DeleteBreakdown"][];
            ejemplos_por_modelo: {
                [key: string]: string[];
            };
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        FormField: {
            name: string;
            label: string;
            type: string;
            required: boolean;
            disabled: boolean;
            help: string;
            value: unknown;
            choices: components["schemas"]["Choice"][];
            min: string;
            max: string;
            step: string;
            graduacion_opcional: boolean;
            file_url: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        FormSchema: {
            kind: string;
            fields: components["schemas"]["FormField"][];
            back: string;
            instrucciones: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        Itinerario: {
            id: number;
            codigo: string;
            provincia: string;
            estado: string;
            estado_label: string;
            /** Format: date */
            fecha_inicio: string;
            /** Format: date */
            fecha_fin: string;
            referente: string;
            localidades: string;
            observaciones: string;
            referente_telefono: string;
            referente_email: string;
            jornadas_total: number | null;
            jornadas?: components["schemas"]["Jornada"][];
            carta_archivo_estado?: string;
            carta_referencia_estado?: string;
            carta_archivo_url?: string;
            carta_referencia?: string;
            subsanacion_observaciones?: string;
            estados_evaluacion?: components["schemas"]["Choice"][];
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        ItinerarioEditInput: {
            provincia: number;
            /** Format: date */
            fecha_inicio: string;
            /** Format: date */
            fecha_fin: string;
            referente_nombre: string;
            referente_apellido?: string;
            referente_telefono?: string;
            referente_email?: string;
            /** Format: uri */
            carta_archivo?: string;
            observaciones?: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        ItinerarioInput: {
            provincia: number;
            /** Format: date */
            fecha_inicio: string;
            /** Format: date */
            fecha_fin: string;
            referente_nombre: string;
            referente_apellido?: string;
            referente_telefono?: string;
            referente_email?: string;
            /** Format: uri */
            carta_archivo?: string;
            observaciones?: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        ItinerarioPage: {
            count: number;
            next: string | null;
            previous: string | null;
            results: components["schemas"]["Itinerario"][];
            estados?: components["schemas"]["Choice"][];
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        Jornada: {
            id: number;
            itinerario_id: number;
            /** Format: date */
            fecha: string;
            sede: string;
            localidad: string;
            ubicacion_url: string;
            latitud: string;
            longitud: string;
            vehiculos: string[];
            direccion: string;
            estado: string;
            estado_label: string;
            referente: string;
            referente_telefono: string;
            equipo_asignado: string;
            observaciones: string;
            registros_total: number | null;
            mapa_query?: string;
            checklist?: components["schemas"]["Checklist"][];
            registros?: components["schemas"]["Registro"][];
            laboratorio?: components["schemas"]["Laboratorio"][];
            cierre?: components["schemas"]["Cierre"] | null;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        JornadaHistoricalInput: {
            /** Format: date */
            fecha: string;
            sede: string;
            localidad?: number | null;
            ubicacion_url: string;
            direccion?: string;
            vehiculos?: number[];
            /** Format: time */
            horario_inicio?: string | null;
            /** Format: time */
            horario_fin?: string | null;
            referente_dni?: string;
            referente_sexo?: string;
            referente_telefono?: string;
            observaciones?: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        JornadaInput: {
            renaper_estado?: string;
            referente_nombre_renaper?: string;
            referente_apellido_renaper?: string;
            /** Format: date */
            fecha: string;
            sede: string;
            localidad?: number | null;
            ubicacion_url: string;
            direccion?: string;
            vehiculos?: number[];
            /** Format: time */
            horario_inicio?: string | null;
            /** Format: time */
            horario_fin?: string | null;
            referente_dni?: string;
            referente_sexo?: string;
            referente_telefono?: string;
            observaciones?: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        Laboratorio: {
            id: number;
            registro_id: number;
            persona: string;
            estado: string;
            siguiente: string | null;
            historial: components["schemas"]["LaboratorioHistory"][];
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        LaboratorioHistory: {
            /** Format: date-time */
            fecha: string;
            antes: string;
            despues: string;
            responsable: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        LaboratorioInput: {
            estado: string;
            /** Format: date */
            fecha: string;
            responsable: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        LaboratorioPage: {
            count: number;
            next: string | null;
            previous: string | null;
            results: components["schemas"]["Laboratorio"][];
        };
        LocationInput: {
            ubicacion_url: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        LocationPreview: {
            success: boolean;
            ubicacion_url: string;
            query: string;
            direccion: string;
            latitud: string;
            longitud: string;
        };
        /**
         * @description * `baja_logica` - baja_logica
         *     * `borrado_fisico` - borrado_fisico
         * @enum {string}
         */
        ModoEnum: "baja_logica" | "borrado_fisico";
        /**
         * @description * `delete` - delete
         * @enum {string}
         */
        OperacionEnum: "delete";
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        Options: {
            provincias: components["schemas"]["ProvinceOption"][];
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        ProvinceOption: {
            id: number;
            nombre: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        Registro: {
            id: number;
            dni: string;
            nombre: string;
            apellido: string;
            numero_acta: string;
            resultado: string;
            cantidad_lentes: number;
            graduacion_izquierda: string;
            graduacion_derecha: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        RegistroHistoricalInput: {
            dni?: string;
            sexo?: string;
            identificador_alternativo?: string;
            nombre: string;
            apellido: string;
            edad?: number | null;
            genero?: string;
            telefono?: string;
            escuela_sede?: string;
            numero_acta: string;
            numero_sobre?: string;
            /** Format: date */
            fecha_atencion: string;
            /** Format: decimal */
            graduacion_izquierda?: string | null;
            /** Format: decimal */
            graduacion_derecha?: string | null;
            resultado: string;
            cantidad_lentes: number;
            /** Format: uri */
            adjunto?: string;
            primera_vez_anteojos?: boolean;
            observaciones?: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        RegistroInput: {
            renaper_estado?: string;
            guardar_continuar?: string;
            dni?: string;
            sexo?: string;
            identificador_alternativo?: string;
            nombre: string;
            apellido: string;
            edad?: number | null;
            genero?: string;
            telefono?: string;
            escuela_sede?: string;
            numero_acta: string;
            numero_sobre?: string;
            /** Format: date */
            fecha_atencion: string;
            /** Format: decimal */
            graduacion_izquierda?: string | null;
            /** Format: decimal */
            graduacion_derecha?: string | null;
            resultado: string;
            cantidad_lentes: number;
            /** Format: uri */
            adjunto?: string;
            primera_vez_anteojos?: boolean;
            observaciones?: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        RegistroPage: {
            count: number;
            next: string | null;
            previous: string | null;
            results: components["schemas"]["Registro"][];
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        Renaper: {
            success: boolean;
            message: string;
            data?: {
                [key: string]: unknown;
            };
            datos_api?: unknown;
            ciudadano_created?: boolean;
            ciudadano_pendiente_creacion?: boolean;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        Sede: {
            id: number;
            nombre: string;
            cueanexo: string | null;
            jurisdiccion: string;
            localidad: string;
            domicilio: string;
            telefono: string;
            mail: string;
            checklist_aprobado: boolean;
            mapa_query: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        SedeInput: {
            sector?: string;
            ambito?: string;
            departamento?: string;
            codigo_departamento?: string;
            localidad: string;
            codigo_localidad?: string;
            cueanexo?: string;
            nombre: string;
            domicilio: string;
            codigo_postal?: string;
            telefono?: string;
            mail?: string;
            provincia: number;
            electricidad_cumple?: string;
            electricidad_observacion?: string;
            /** Format: uri */
            electricidad_evidencia?: string;
            viandas_cumple?: string;
            viandas_observacion?: string;
            /** Format: uri */
            viandas_evidencia?: string;
            seguridad_cumple?: string;
            seguridad_observacion?: string;
            /** Format: uri */
            seguridad_evidencia?: string;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        SedePage: {
            count: number;
            next: string | null;
            previous: string | null;
            results: components["schemas"]["Sede"][];
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        SedeUpdateInput: {
            sector?: string;
            ambito?: string;
            departamento?: string;
            codigo_departamento?: string;
            localidad: string;
            codigo_localidad?: string;
            cueanexo?: string;
            nombre: string;
            domicilio: string;
            codigo_postal?: string;
            telefono?: string;
            mail?: string;
            provincia: number;
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        Session: {
            username: string;
            can_view_itinerarios: boolean;
            can_add_itinerarios: boolean;
            can_view_sedes: boolean;
            can_export: boolean;
            permissions: {
                [key: string]: boolean;
            };
        };
        /** @description Contrato de salida: las escrituras usan los ModelForms compartidos. */
        SubsanacionInput: {
            /** Format: uri */
            carta_archivo: string;
        };
        VpslFormInput: components["schemas"]["ItinerarioInput"] | components["schemas"]["SedeInput"] | components["schemas"]["JornadaInput"] | components["schemas"]["RegistroInput"] | components["schemas"]["ChecklistInput"] | components["schemas"]["LaboratorioInput"] | components["schemas"]["CierreInput"] | components["schemas"]["SubsanacionInput"] | components["schemas"]["ItinerarioEditInput"] | components["schemas"]["SedeUpdateInput"] | components["schemas"]["RegistroHistoricalInput"] | components["schemas"]["JornadaHistoricalInput"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    actions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletePreview"];
                };
            };
        };
    };
    actions_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ActionInput"];
                "application/x-www-form-urlencoded": components["schemas"]["ActionInput"];
                "multipart/form-data": components["schemas"]["ActionInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResult"];
                };
            };
        };
    };
    exports_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
    forms_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormSchema"];
                };
            };
        };
    };
    forms_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["VpslFormInput"];
                "application/x-www-form-urlencoded": components["schemas"]["VpslFormInput"];
                "multipart/form-data": components["schemas"]["VpslFormInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResult"];
                };
            };
        };
    };
    vpsl_itinerarios_list: {
        parameters: {
            query?: {
                estado?: string;
                page?: number;
                page_size?: number;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItinerarioPage"];
                };
            };
        };
    };
    vpsl_itinerarios_create: {
        parameters: {
            query?: {
                estado?: string;
                page?: number;
                page_size?: number;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItinerarioInput"];
                "application/x-www-form-urlencoded": components["schemas"]["ItinerarioInput"];
                "multipart/form-data": components["schemas"]["ItinerarioInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Itinerario"];
                };
            };
        };
    };
    vpsl_itinerario_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Itinerario"];
                };
            };
        };
    };
    jornadas_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jornada"];
                };
            };
        };
    };
    jornadas_laboratorio_retrieve: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LaboratorioPage"];
                };
            };
        };
    };
    jornadas_registros_retrieve: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroPage"];
                };
            };
        };
    };
    options_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Options"];
                };
            };
        };
    };
    renaper_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Renaper"];
                };
            };
        };
    };
    vpsl_sedes: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SedePage"];
                };
            };
        };
    };
    vpsl_sede_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sede"];
                };
            };
        };
    };
    session_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    ubicacion_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationInput"];
                "application/x-www-form-urlencoded": components["schemas"]["LocationInput"];
                "multipart/form-data": components["schemas"]["LocationInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationPreview"];
                };
            };
        };
    };
}
