# Generated by Django 5.2.16 on 2026-09-28 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encuestas", "0004_encuesta_aprobacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="encuesta",
            name="fecha_rechazo",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha del último rechazo"
            ),
        ),
        migrations.AddField(
            model_name="encuesta",
            name="motivo_rechazo",
            field=models.TextField(
                blank=True,
                default="",
                max_length=2000,
                verbose_name="Motivo del último rechazo",
            ),
        ),
        migrations.AddField(
            model_name="encuesta",
            name="usuario_rechazo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="encuestas_rechazadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Último rechazo por",
            ),
        ),
    ]
