# Generated by Django 5.2.16 on 2026-09-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0061_comedor_responsable_tarjeta_municipio"),
        ("comedores", "0062_imagencomedor_subido_por"),
    ]

    operations = []
