# Generated by Django 5.2.16 on 2026-09-28 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encuestas", "0005_motivo_rechazo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentacionencuesta",
            name="usuarios",
            field=models.ManyToManyField(
                blank=True,
                related_name="segmentaciones_encuestas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuarios destinatarios",
            ),
        ),
        migrations.AlterField(
            model_name="segmentacionencuesta",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("todos_los_usuarios", "Todos los usuarios"),
                    ("listado_documentos", "Listado de documentos"),
                    ("listado_usuarios", "Listado de IDs de usuarios"),
                ],
                max_length=20,
                verbose_name="Tipo de segmentación",
            ),
        ),
    ]
