# Generated by Django 5.2.16 on 2026-09-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("encuestas", "0006_segmentacion_usuarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentacionencuesta",
            name="grupos",
            field=models.ManyToManyField(
                blank=True,
                related_name="segmentaciones_encuestas",
                to="auth.group",
                verbose_name="Grupos destinatarios",
            ),
        ),
        migrations.AlterField(
            model_name="segmentacionencuesta",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("todos_los_usuarios", "Todos los usuarios"),
                    ("listado_documentos", "Listado de documentos"),
                    ("listado_usuarios", "Listado de IDs de usuarios"),
                    ("grupos", "Grupos de usuarios"),
                ],
                max_length=20,
                verbose_name="Tipo de segmentación",
            ),
        ),
    ]
