# Generated by Django 5.2.16 on 2026-10-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centrodeinfancia", "0049_catalogos_intervencion_kernel"),
    ]

    operations = [
        migrations.AddField(
            model_name="centrodeinfancia",
            name="campos_verificados_renaper",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="nominacentroinfancia",
            name="campos_verificados_renaper",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
