# Generated by Django 5.2.16 on 2026-10-06 15:16

from django.db import migrations, models


def completar_estado_y_responsable(apps, schema_editor):
    """Estado desde ``activo`` y un responsable por CDI.

    El responsable es el acceso activo cuyo email coincide con el del referente
    de la ficha; si ninguno coincide, el acceso activo más antiguo. Un CDI sin
    accesos activos queda sin responsable hasta que se guarde su ficha.
    """
    AccesoCDI = apps.get_model("centrodeinfancia", "AccesoCDI")
    AccesoCDI.objects.filter(activo=False).update(estado="baja")
    AccesoCDI.objects.filter(activo=True).update(estado="activo")

    centros = (
        AccesoCDI.objects.filter(activo=True)
        .values_list("centro_id", flat=True)
        .distinct()
    )
    for centro_id in centros:
        activos = AccesoCDI.objects.filter(centro_id=centro_id, activo=True)
        email_referente = (
            activos.values_list("centro__email_referente", flat=True).first() or ""
        ).strip()
        responsable = None
        if email_referente:
            responsable = (
                activos.filter(user__email__iexact=email_referente)
                .order_by("pk")
                .first()
            )
        responsable = responsable or activos.order_by("pk").first()
        AccesoCDI.objects.filter(pk=responsable.pk).update(es_responsable=True)


class Migration(migrations.Migration):

    dependencies = [
        ("centrodeinfancia", "0050_campos_verificados_renaper"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesocdi",
            name="es_responsable",
            field=models.BooleanField(
                default=False,
                help_text="Referente vigente de la ficha: administra los usuarios del CDI.",
            ),
        ),
        migrations.AddField(
            model_name="accesocdi",
            name="estado",
            field=models.CharField(
                choices=[
                    ("activo", "Activo"),
                    ("suspendido", "Suspendido"),
                    ("baja", "Baja"),
                ],
                default="activo",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="accesocdi",
            name="motivo_estado",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Motivo de la última suspensión o baja.",
            ),
        ),
        migrations.RunPython(completar_estado_y_responsable, migrations.RunPython.noop),
    ]
