# Generated by Django 5.2.16 on 2026-09-27 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0059_comedorpwacreateoperation"),
        ("relevamientos", "0017_altas_desde_app_n15_n18"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SeguimientoPnud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_validacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Pendiente validación coordinador",
                                "Pendiente validación coordinador",
                            ),
                            ("A subsanar", "A subsanar"),
                            ("Validado", "Validado"),
                        ],
                        help_text="Vacío = todavía no se envió a validación del coordinador.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "observaciones_coordinador",
                    models.TextField(
                        blank=True,
                        help_text="Qué debe corregir el territorial cuando queda 'A subsanar'.",
                        null=True,
                    ),
                ),
                (
                    "fecha_revision_coordinador",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[("sisoc", "SISOC"), ("app", "App territorial")],
                        default="sisoc",
                        max_length=16,
                    ),
                ),
                (
                    "asignado_desde_sisoc",
                    models.BooleanField(
                        default=True,
                        help_text="False cuando lo autoactivó el territorial desde la app.",
                    ),
                ),
                (
                    "client_uuid",
                    models.CharField(
                        blank=True,
                        help_text="Identificador estable del cliente para deduplicar reintentos offline del alta. En MySQL los NULL son distintos, así que solo enforcea cuando viene informado.",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "formulario",
                    models.CharField(
                        choices=[
                            (
                                "secos",
                                "FORM-PNUD-SECOS — Seguimiento Puntos de Entrega (Línea Secos)",
                            ),
                            (
                                "iia1",
                                "FORM II A.1 — Virtual · Presencial y Vianda (Línea Tradicional)",
                            ),
                            (
                                "iib1",
                                "FORM II B.1 — Virtual · Módulo (Línea Tradicional)",
                            ),
                            (
                                "iia",
                                "FORM II A — Presencial · Vianda (Línea Tradicional)",
                            ),
                            (
                                "iib",
                                "FORM II B — Presencial · Módulo (Línea Tradicional)",
                            ),
                        ],
                        max_length=8,
                    ),
                ),
                ("fecha_hora", models.DateTimeField(blank=True, null=True)),
                ("datos", models.JSONField(blank=True, default=dict)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "comedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos_pnud",
                        to="comedores.comedor",
                    ),
                ),
                (
                    "coordinador",
                    models.ForeignKey(
                        blank=True,
                        help_text="Coordinador que hizo la última revisión.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss_revisados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seguimientos_pnud",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguimiento PNUD",
                "verbose_name_plural": "Seguimientos PNUD",
                "ordering": ["-fecha_hora", "-id"],
            },
        ),
    ]
